#! /usr/bin/env bash

if [ -e nekmesh ];then rm nekmesh; fi

echo "Compiling from $1.c"
gcc $1.c -lm -o nekmesh

if [ ! -e nekmesh ];then 
  echo "compilation error!"
  exit
fi

echo ""
./nekmesh -fi $1.inp -rea $1.rea
echo ""
echo "generating re2 file"
reatore2 << EOF
$1
tmp
EOF
rm tmp.rea
mv tmp.re2 $1.re2
